name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '15 1 * * 6'

jobs:
  checks_and_builds:
    strategy:
      fail-fast: false
      matrix:
        action:
          - doc
          - fmt
          - check
          - clippy
          - test
          - build
          - build-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: install rust
        run: curl --proto '=https' --tlsv1.3 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
      - name: act
        run: .github/scripts/ci.bash ${{ matrix.action }}
